# Deploy solutions using a given solution configuration to different environments
# Needs to be started manually

# No automated trigger
trigger: none

resources:
  repositories:
    # Add a reference to the pipelinetemplates repository where all the templates are located
    # No need to clone them, the templates can be referenced directly
    - repository: pipelinetemplates
      type: github
      name: DIGITALLNature/DigitallPipelines
      endpoint: DIGITALL Pipelines Service Connection

      # By default the default branch is used. If this is not the same default between projects
      # (for most it is main, but for some it still is master) or a different one should be
      # used, the ref mus be set:
      # ref: refs/heads/preview
      # ref: refs/heads/master

  pipelines:
    # Add a reference to the pipeline exporting the solutions
    # Runs whenever the export solutions ran
    # > This requires the export solutions to be configured with matching name and tags
    - pipeline: export-solution-configuration
      source: Export solutions
      trigger:
        tags:
          - Environment_Development
          - Trigger_Release

# By default use an ubuntu image
pool:
  vmImage: ubuntu-latest

# Use existing variable template
variables:
  - template: ../../deployment-settings/solution-configuration/solution-configuration.yml

# Extends from pipeline template that imports in stages
extends:
  template: azure-pipeline-templates/pp-solution-import/import-stages.yml@pipelinetemplates
  parameters:
    solutionList: ${{ variables.SolutionConfigList }}
    solutionListReverse: ${{ variables.SolutionConfigListReverse }}
    triggerPipeline: Export solutions

    # List of environments and information about them
    # Every environment will become its own stage in the pipeline
    environments:

      - friendlyName: Test
        uniqueName: test
        serviceConnection: Power Platform Service Connection Test
        variables:
          - group: Power Platform Environment Test

      - friendlyName: Production
        uniqueName: prod
        serviceConnection: Power Platform Service Connection Prod
        devOpsEnvironment: Power Platform Environment Prod
        variables:
          - group: Power Platform Environment Prod