# Part 01 of test scenario "Rollback first import"
# Import solutions which should trigger a rollback

# No automated trigger; pipeline trigger is used
trigger: none

resources:
  repositories:
    - repository: pipelinetemplates
      type: github
      name: DIGITALLNature/DigitallPipelines
      endpoint: "(TEST CI) DIGITALL Pipelines Test"

  pipelines:
    - pipeline: import
      source: (TEST CI) 00 Rollback first import - prepare
      trigger: true

pool:
  vmImage: ubuntu-latest

variables:
  - template: ../deployment-settings/solution-configuration/solution-configuration.yml

extends:
  template: azure-pipeline-templates/pp-solution-import/import-stages.yml@pipelinetemplates
  parameters:
    solutionList: ${{ variables.SolutionConfigList }}
    solutionListReverse: ${{ variables.SolutionConfigListReverse }}
    solutionFolder: $(Build.Repository.LocalPath)/azure-pipeline-tests/pp-solution-import-rollback-first/solutions

    environments:
      - friendlyName: Test
        uniqueName: test
        serviceConnection: "(TEST CI) Test Solution Conn"
        devOpsEnvironment: "(TEST CI) Test Solution Env"
        variables:
          - group: "(TEST CI) Test Solution Url"

    continueOnDeploymentFailure: true
