variables:
  SolutionConfigList: test_ci_pp_solution_import_rollback_patch_Patch_ac05d939,test_ci_pp_solution_import_rollback_patch_fail
  SolutionConfigListReverse: test_ci_pp_solution_import_rollback_patch_fail,test_ci_pp_solution_import_rollback_patch_Patch_ac05d939
