# Configure global git config to use git commands

parameters:
  # ----- Optional predefined parameters -----

  # Will be used for git user.email
  - name: userMail
    displayName: Git user mail used for commits
    type: string
    default: info@digitall.com

  # Will be used for git user.name
  - name: userName
    displayName: Git user name used for commits
    type: string
    default: pipeline

  # Path to the git repository
  - name: path
    displayName: Path to git repository
    type: string
    default: '$(Build.Repository.LocalPath)'

steps:
  # Configure git with user name and user email
  - task: PowerShell@2
    displayName: Configure git config
    inputs:
      targetType: inline
      workingDirectory: ${{ parameters.path }}
      script: |
        $Debug = $env:Debug
        $UserEmail = $env:UserEmail
        $UserName = $env:UserName
        $WorkingDirectory = $env:WorkingDirectory

        if ($Debug -eq $True) {
          Write-Host "##[debug]UserEmail=$UserEmail"
          Write-Host "##[debug]UserName=$UserName"
          Write-Host "##[debug]WorkingDirectory=$WorkingDirectory"
        }

        git config --global user.email "$UserEmail"
        git config --global user.name "$UserName"
    env:
      Debug: $(System.Debug)
      UserEmail: ${{ parameters.userMail }}
      UserName: ${{ parameters.userName }}
      WorkingDirectory: ${{ parameters.path }}